export declare const ERROR_MODULE_NOT_EXIST = "ERROR_MODULE_NOT_EXIST";
export declare const ERROR_MODULE_UNREACHABLE = "ERROR_MODULE_UNREACHABLE";
export declare const ERROR_MODULE_FORBIDDEN = "ERROR_MODULE_FORBIDDEN";
